### PR TITLE
Feat/update dependencies

### PR DESCRIPTION
**Pull request by restanrm**
Hello, I've got some issues with recent version of influxdb (see [Issue 2822]), and some fixes have been pushed.

The goal of this PR is to update the dependencies to latest version. 

[Issue 2822]: https://github.com/influxdata/telegraf/issues/2822

### CODE REVIEW

**Comment by carlpett** [comment]
Looks good, thanks! Would you mind updating the CI (.circleci/config.yml) as well?

**Comment by restanrm** [comment]
I tried to update my PR to add modifications to `.circleci/config.yaml` but I never played with that and don't know how to test, sorry.

**Comment by carlpett** [comment]
Ah, it should have been running automatically, but apparently I hadn't enabled automatically building PRs from forks.
I fixed that now, so going forward it will build automatically when new PRs are opened. I also pushed a small fix that was necessary with the change to using modules.

Thanks a lot for helping out with this!

**Comment by carlpett** [comment]
I just tagged 0.1.1, so there should be binaries available soon, too.

**Pull request merged**
